[package]
name = "electro_solve_core"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra.workspace = true
num-complex.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
approx.workspace = true